In [1]:
import numpy as np
import pandas as pd

In [2]:
obj= pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
"b" in obj2

True

In [5]:
pd.isna(obj2)

d    False
b    False
a    False
c    False
dtype: bool

In [6]:
pd.notna(obj2)

d    True
b    True
a    True
c    True
dtype: bool

In [7]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [8]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [9]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [10]:
frame.head(2)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [11]:

frame.tail(3)

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [12]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [13]:
states=["Texas","Utah","California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [14]:
frame.reindex(states,axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [15]:
frame.drop(columns=["Texas"])

   Ohio  California
a     0           2
c     3           5
d     6           8

**FROM HERE ON:**

In [16]:
obj=pd.Series([4,5,-3,6])
obj

0    4
1    5
2   -3
3    6
dtype: int64

In [17]:
obj.index=['a','b','c','d']

exponential of the values

In [18]:
np.exp(obj)

a     54.598150
b    148.413159
c      0.049787
d    403.428793
dtype: float64

In [19]:
print("b" in obj)
print("e" in obj)

True
False

In [20]:
s_dict={"Ohio":1000,"Toronto":2000,"Texas":3000,"California":4000}
obj2=pd.Series(s_dict)
obj2

Ohio          1000
Toronto       2000
Texas         3000
California    4000
dtype: int64

In [21]:
states=["Ohio","Texas","Oregon","California"]
obj3=pd.Series(s_dict,index=states)
obj3

Ohio          1000.0
Texas         3000.0
Oregon           NaN
California    4000.0
dtype: float64

In [22]:
print(pd.notna(obj3),"\n")
print(pd.isna(obj3))

Ohio           True
Texas          True
Oregon        False
California     True
dtype: bool

Ohio          False
Texas         False
Oregon         True
California    False
dtype: bool

In [23]:
obj3.isna()

Ohio          False
Texas         False
Oregon         True
California    False
dtype: bool

In [24]:
obj2 + obj3

California    8000.0
Ohio          2000.0
Oregon           NaN
Texas         6000.0
Toronto          NaN
dtype: float64

In [26]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [29]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [30]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [31]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [32]:
frame2["state"]
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [33]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [34]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [38]:
frame2["debt"] = np.arange(6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [39]:
del frame2["debt"]
frame2.columns

Index(['year', 'state', 'pop'], dtype='object')

In [41]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3=pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [42]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [43]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [44]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [45]:
frame3
frame3.columns
print("Ohio" in frame3.columns)
2003 in frame3.index

True

False

In [46]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 3])
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    yellow
4    yellow
5    yellow
dtype: object

In [56]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

In [48]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [49]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [50]:
d1=data.iloc[:,:3]

In [51]:
d1

          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [52]:
data.iloc[:,:3]

          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [57]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)
df1 + df2

   A
0  1
1  2
   B
0  3
1  4

    A   B
0 NaN NaN
1 NaN NaN

In [58]:
df1.add(df2, fill_value=0)

     A    B
0  1.0  3.0
1  2.0  4.0

In [59]:
df1.add(df2)

    A   B
0 NaN NaN
1 NaN NaN

In [60]:
df1.reindex(columns=df2.columns, fill_value=0)

   B
0  0
1  0

In [61]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]

In [62]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [63]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [64]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [65]:
frame + series

          b     d     e
Utah    0.0   2.0   4.0
Ohio    3.0   5.0   7.0
Texas   6.0   8.0  10.0
Oregon  9.0  11.0  13.0

In [68]:
frame.sub(series)

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [69]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

b    9.0
d    9.0
e    9.0
dtype: float64

In [70]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

       b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

In [71]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

           b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [72]:
frame["e"].map(my_format)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object