In [ ]:
import pandas as pd

# create a Pandas Series of datetime values

In [ ]:
dates=pd.Series(['2022-01-01','2022-02-01','2022-03-01'])
dt_values=pd.to_datetime(dates)
dt_values

0   2022-01-01
1   2022-02-01
2   2022-03-01
dtype: datetime64[ns]

# print the year component of each datetime value

In [ ]:
yrs=dt_values.dt.year
print(yrs)

0    2022
1    2022
2    2022
dtype: int64

Parsing XML with Ixml.objectify

In [ ]:
from lxml import objectify
path='Performance_MNR (1).xml'
parsed=objectify.parse(open(path))
root=parsed.getroot()

In [ ]:
root.INDICATOR

In [ ]:
root

In [ ]:
data=[]
skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
'DESIRED_CHANGE', 'DECIMAL_PLACES']

for elt in root.INDICATOR:
  el_data = {}
  for child in elt.getchildren():
    if child.tag in skip_fields:
      continue
    el_data[child.tag] = child.pyval
  data.append(el_data) 
perf=pd.DataFrame(data)
perf

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8
...,...,...,...,...,...,...,...,...,...,...,...,...
643,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,8,Service Indicators,M,%,97.0,,97.0,
644,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,9,Service Indicators,M,%,97.0,,97.0,
645,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,10,Service Indicators,M,%,97.0,,97.0,
646,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,11,Service Indicators,M,%,97.0,,97.0,
647,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,%,97.0,,97.0,

In [ ]:
perf.columns

Index(['AGENCY_NAME', 'INDICATOR_NAME', 'DESCRIPTION', 'PERIOD_YEAR',
       'PERIOD_MONTH', 'CATEGORY', 'FREQUENCY', 'INDICATOR_UNIT', 'YTD_TARGET',
       'YTD_ACTUAL', 'MONTHLY_TARGET', 'MONTHLY_ACTUAL'],
      dtype='object')

In [ ]:
perf.index

RangeIndex(start=0, stop=1, step=1)

#*Binary data formats*

In [ ]:
frame=pd.read_csv('ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
frame.to_pickle('frame_pickle')

In [ ]:
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

*HDF5* *FORMAT*

In [ ]:
import numpy as np

In [ ]:
frame2=pd.DataFrame({'a':np.random.randn(100)})
frame2

           a
0   0.276208
1   0.403676
2  -0.105427
3  -1.132704
4   0.203701
..       ...
95  0.721219
96 -0.018818
97 -0.387876
98 -0.010754
99  0.863210

[100 rows x 1 columns]

In [ ]:
store=pd.HDFStore('mydata.h5')
store['obj1']=frame2
store['obj_col']=frame2['a']

In [ ]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [ ]:
store['obj1']

           a
0   0.276208
1   0.403676
2  -0.105427
3  -1.132704
4   0.203701
..       ...
95  0.721219
96 -0.018818
97 -0.387876
98 -0.010754
99  0.863210

[100 rows x 1 columns]

Query operations on HDFStore

In [ ]:
store.put('obj2',frame2,format='table')

In [ ]:
store.select('obj2',where=['index >= 10 and index <15'])

           a
10  1.563639
11  1.619887
12 -0.245094
13  1.346435
14  0.659253

In [ ]:
store.close()

Another way to use these query tools

In [ ]:
frame2.to_hdf('mydata.h5','obj3',format='table')
pd.read_hdf('mydata.h5','obj3',where=['index<3'])

          a
0  0.276208
1  0.403676
2 -0.105427

#Read excel files

In [ ]:
xlsx=pd.ExcelFile('ex1.xlsx')

In [ ]:
frame=pd.read_excel(xlsx,'Sheet1')

In [ ]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

pandas data to excel format using

In [ ]:
writer=pd.ExcelWriter("myex2.xlsx")
frame.to_excel(writer,'Sheet1')
writer.save()

passing file path to to_excel

In [ ]:
frame.to_excel('myex2.xlsx')

Web APIs
github issues

In [ ]:
import requests
url= 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [ ]:
resp=requests.get(url)
resp

In [ ]:
d=resp.json()

In [ ]:
type(d)

list

In [ ]:
issues = pd.DataFrame(d,columns=['number','title','labels','state'])
issues

,number,title,labels,state
0,51752,BUG: converting a `string[pyarrow]` column to ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
1,51751,API: Should groupby.rolling be treated as a tr...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
2,51750,PERF: groupby.value_counts,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
3,51749,DEPR: NDFrame.bool,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
4,51748,ENH: Allow dictionaries to be passed to pandas...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
5,51747,STYLE enable ruff PLR5501 #51709,[],open
6,51745,improve explanation of linear interpolation in...,[],open
7,51744,BUG: clipboard does not work on wayland,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
8,51741,BUG: indexing empty pyarrow backed object retu...,"[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...",open
9,51740,STYLE enable ruff TCH,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
10,51738,PERF: accessing sliced indexes with populated ...,[],open
11,51737,"BUG: with mode.dtype_backend='pyarrow', conver...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
12,51736,Is ExtensionDtype.type a property or a ClassVar?,[],open
13,51734,BUG: `pd.concat` fails with `GroupBy.head()` a...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
14,51732,CoW: Add property for references to series class,"[{'id': 2085877452, 'node_id': 'MDU6TGFiZWwyMD...",open
15,51731,CoW: Implement copy by default for df construc...,[],open
16,51730,PERF: ArrowExtensionArray._from_sequence_of_st...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
17,51727,BUG: assert_frame_equal failed on comparing tw...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,51726,BUG: read_parquet does not respect index for a...,"[{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...",open
19,51725,BUG: Change in default column index dtype,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,51723,CI: Add bot to track deprecation prs,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
21,51722,PERF: GroupBy.quantile,[],open
22,51721,BUG: bytes of special nan lost with .loc/.iloc,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,51720,"BUG: read_parquet(list_of_files, engine='fastp...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
24,51718,BUG: tz_convert not implemented for arrow time...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,51717,BUG: pd.read_parquet drops indexes when mode.d...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,51716,"BUG: Incorrect freqstr ""D"" after timezone conv...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,51710,"WARN/ERR: raise on .resample('1M', closed='lef...","[{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...",open
28,51709,STYLE enable ruff PLR5501,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
29,51708,STYLE enable ruff PLW2901,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open

In [ ]:
issues.shape

(30, 4)

#interaction with databases

In [1]:
import sqlite3

In [2]:
query= """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)

In [3]:
con.commit()

In [4]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee','Florida',2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)

In [5]:
con.commit()

In [6]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [10]:
import pandas as pd
pd.DataFrame(rows,columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [11]:
import sqlalchemy as sqla
db=sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5