#create a series which includes some of null values

In [2]:
import pandas as pd
from numpy import nan as NA
S=pd.Series([1,NA,4,NA,NA])
S

0    1.0
1    NaN
2    4.0
3    NaN
4    NaN
dtype: float64

#Check if each element is null or not

In [3]:
S.isnull()

0    False
1     True
2    False
3     True
4     True
dtype: bool

#removing all null values from given series

In [4]:
S.dropna()

0    1.0
2    4.0
dtype: float64

#create a dataframe which includes some null values

In [9]:
data=pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

#remove rows containing null values

In [11]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

remove rows contaning all null values

In [12]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

add a new column which contains only null values

In [15]:
data[4]=NA
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

delete an existing column if it contains all null values

In [16]:
data.dropna(axis=1,how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

create a dataframe of 7rows and 3columns, fill it with random values 
Impute null values starting from row index 0 to row index 3 and column index 1
also impute null values at column label 2 from row index 0 to 1

In [19]:
import numpy as np
df=pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1]=NA
df.iloc[:2,2]=NA
df

          0         1         2
0 -1.087671       NaN       NaN
1  0.205939       NaN       NaN
2  1.688202       NaN -0.702687
3  1.220221       NaN -0.327153
4 -0.629294  1.008163  2.190992
5 -0.505764  0.309613 -0.661454
6 -0.413580  0.307553  1.163622

delete all rows containing null values in above df

In [20]:
df.dropna()

          0         1         2
4 -0.629294  1.008163  2.190992
5 -0.505764  0.309613 -0.661454
6 -0.413580  0.307553  1.163622

delete a row only if it doesnt contain a min of 2 non missing values

In [21]:
df.dropna(thresh=2)

          0         1         2
2  1.688202       NaN -0.702687
3  1.220221       NaN -0.327153
4 -0.629294  1.008163  2.190992
5 -0.505764  0.309613 -0.661454
6 -0.413580  0.307553  1.163622

fill all null values with 0

In [22]:
df.fillna(0)

          0         1         2
0 -1.087671  0.000000  0.000000
1  0.205939  0.000000  0.000000
2  1.688202  0.000000 -0.702687
3  1.220221  0.000000 -0.327153
4 -0.629294  1.008163  2.190992
5 -0.505764  0.309613 -0.661454
6 -0.413580  0.307553  1.163622

fill all missing values at column index 1 with 50 and column index 2 with 100

In [23]:
df.fillna({1:50,2:100})

          0          1           2
0 -1.087671  50.000000  100.000000
1  0.205939  50.000000  100.000000
2  1.688202  50.000000   -0.702687
3  1.220221  50.000000   -0.327153
4 -0.629294   1.008163    2.190992
5 -0.505764   0.309613   -0.661454
6 -0.413580   0.307553    1.163622

fill all null values with forward fill

In [25]:
data.fillna(method='ffill')

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  6.5  3.0 NaN
2  1.0  6.5  3.0 NaN
3  1.0  6.5  3.0 NaN

fill all null values with mean value of the column values

In [27]:
df.fillna(df.mean())

          0         1         2
0 -1.087671  0.541776  0.332664
1  0.205939  0.541776  0.332664
2  1.688202  0.541776 -0.702687
3  1.220221  0.541776 -0.327153
4 -0.629294  1.008163  2.190992
5 -0.505764  0.309613 -0.661454
6 -0.413580  0.307553  1.163622

create following df containing 2 columns k1,k2 [one,2,1,2,1,2],[1,1,2,3,3,4]

In [32]:
df2=pd.DataFrame({'k1':['one','two','one','two','one','two'],'k2':[1,1,2,3,3,3]})
df2

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   3

remove duplicates

In [33]:
df2.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3

create df containing 2 columns name and age. transform age column  using a map method and user defined fn to create a new column age_in_months

In [36]:
data2 = {'name': ['Alice', 'Bob', 'Charlie', 'David'],'age': [25, 30, 35, 40]}
df3 = pd.DataFrame(data2)
df3

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [35]:
def age_in_months(age):
  return age * 12
# use map() to apply the age_in_months function to the age column
df3['age_in_months'] = df3['age'].map(age_in_months)
# print the resulting dataframe
print(df3)

      name  age  age_in_months
0    Alice   25            300
1      Bob   30            360
2  Charlie   35            420
3    David   40            480

In [37]:
print('h',1)

h 1